### ISSUE TITLE
Group Membership

### ISSUE THREAD

**Issue by marshalls** [wells/l4-ldap-ntlm#1]
How do you use the group memberships to control access?  I have it all set up and it's working fine but I'm not sure how to use the group memberships to tell the application what role the user has.  Can you provide some more detail?

**Comment by wells** [comment]
@marshalls, I have a very simple ACL in this codebase. You have admins, auth'd users, and guests. 

You can check what group a user is authenticated as with Auth:user()->group (see the clean function in the L4LdapNtlmUserProvider class). In addition, Auth::user()->type is the ACL value (i.e. 0 = admin,  1 = user). So, you could use type and group to determine roles in your app. 

Mind you, another way to handle roles would be to add an additional User resource stored in a sql db with specified roles for a username. This would be an additional layer and I don't personally use it.
