### ISSUE TITLE
Support for userPricinalName and more

### ISSUE THREAD

**Issue by nesl247** [wells/l4-ldap-ntlm#11]
Please add support to login using any of the UPNs available to a user. This way we can do something like:

`user` - sAMAccountName
`user@domain.com` - userPrincipalName
`user@internal.domain.com` - userPrincipalName
`domain\user`

The benefit to this is that the user can log in using whatever format they are used to using. For instance, there is the username (normal), the email address, and then of course the `user@internal.domain.com` style, which might not be publically accessible, and lastly the older style `domain\user` method.

In my case, we have domain.com which is publically accessible, and is an additional UPN. The domain itself is actually `internal.domain.com`.

**Comment by wells** [comment]
I'll look into it. Definitely a feature worth implementing, and would take hardly any time at all to modify. Do you want to submit a pull request?
