### ISSUE TITLE
Exception class missing

### ISSUE THREAD

**Issue by towel** [wells/l4-ldap-ntlm#2]
L4LdapNtlmUserProvider.php fails to throw an exception in case an AD server is unreachable (L4LdapNtlmUserProvider.php line 44):

```
Class 'Wells\L4LdapNtlm\Exception' not found
```

( Symfony \ Component \ Debug \ Exception \ FatalErrorException )

Please add this class. Thanks! :)

**Comment by wells** [comment]
Yeah, I saw that when my AD went offline the other day. My mistake. Fixed by changing to `\Exception`
