### ISSUE TITLE
please support in laravel 4.1

### ISSUE THREAD

**Issue by nadavvin** [wells/l4-ldap-ntlm#3]
laravel 4.1 released, please update the compatibility.

**Comment by nickdenardis** [comment]
+1

**Comment by wells** [comment]
I'm using it in 4.1 now without issues. Are there any specific errors for you two?

**Comment by syphernl** [comment]
Your composer.json still explicitly wants illuminate/support 4.0.x so it cannot be installed on a (clean) Laravel 4.1 install.

**Comment by wells** [comment]
I'll update it. Thanks.
