### ISSUE TITLE
Multiple Domain Controllers

### ISSUE THREAD

**Issue by nesl247** [wells/l4-ldap-ntlm#5]
Looking at the configuration example, it appears only one host is supported. We have multiple domain controllers for fault tolerance as many companies do.

Would it be possible to make the host key point to an array instead of a single string entry?

Then l4-ldap-ntlm would attempt to connect to each host until it has exhausted the array or a host connects?

**Comment by wells** [comment]
@nesl247 I'll aim for multiple DNS/AD hosts this in the next release for sure. Expect some other good changes too, involving route name based user/group multilevel authentication DB table.

For now, you could simply move the code from vendor to workbench, change the config host to hosts with an array of strings and edit the code in `__construct()` to loop through the hosts array...
