### ISSUE TITLE
"Must be declared abstract" error

### ISSUE THREAD

**Issue by WorldWideWebb** [wells/l4-ldap-ntlm#7]
I just ran composer update again this morning, and after I did that, I'm now getting the following error when attempting a login:

```
Symfony \ Component \ Debug \ Exception \ FatalErrorException
Class Wells\L4LdapNtlm\L4LdapNtlmUserProvider contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Auth\UserProviderInterface::retrieveByToken, Illuminate\Auth\UserProviderInterface::updateRememberToken)
```

Everything was working fine earlier this morning, and I've reverted any code changes back to where they were previously, but no dice. Any ideas to point me in the right direction?

**Comment by wells** [comment]
Just ran into it today too. 

That is to do with the update to laravel's UserProvider interface in 4.1.26. Your options are either to rollback the framework to 4.1.25 or add code like this into L4LdapNtlmUserProvider.php. I'm planning on having a new version of this package, hopefully before Laracon, which will implement remember me tokens using a db along with some other really nice route based features that I mentioned in another issue.

``` php
     /**
     * Retrieve a user by by their unique identifier and "remember me" token.
     *
     * @param  mixed  $identifier
     * @param  string  $token
     * @return \Illuminate\Auth\UserInterface|null
     */
    public function retrieveByToken($identifier, $token)
    {
        return $this->retrieveByID($identifier);
    }

    /**
     * Update the "remember me" token for the given user in storage.
     *
     * @param  \Illuminate\Auth\UserInterface  $user
     * @param  string  $token
     * @return void
     */
    public function updateRememberToken(UserInterface $user, $token)
    {
        $user->setRememberToken($token);
    }
```

**Comment by WorldWideWebb** [comment]
Thanks for the quick reply. I assumed it had to be framework-related, since I ran a quick experiment with another provider this morning and got a similar result.
