### ISSUE TITLE
Support for Laravel 4.1.26

### ISSUE THREAD

**Issue by rhufsky** [wells/l4-ldap-ntlm#9]
According to http://laravel.com/docs/upgrade#upgrade-4.1.26, Laravel has introduced security improvements for "remember me" cookies. This also includes two new methods in UserProviderInterface. This sems to break L4LdapNtlmUserProvider as it currently does not implement these  methods.

I implemented a workaround in my local copy which does not make me completely happy but for now it works:

```
    public function retrieveByToken($identifier, $token){
        throw new \Predis\NotSupportedException();
    }

    public function updateRememberToken(UserInterface $user, $token) {
        throw new \Predis\NotSupportedException();
    }
```

**Comment by woganmay** [comment]
+1, I've run into this as well. I'm forced to downgrade to v4.1.25 until this is fixed.

**Comment by wells** [comment]
I'll be doing a major rework/rename of this library this month. Another quick fix is to not save the token in the UserProvider and the User model.
